spring.application.name=productserviceflux

security.basic.users[0].username=admin
security.basic.users[0].password=adminpass
security.basic.users[0].role=ADMIN

security.basic.users[1].username=user
security.basic.users[1].password=userpass
security.basic.users[1].role=USER

server.port=8080
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/postgres
spring.r2dbc.username=postgres
spring.r2dbc.password=12345
